library(reshape2)
features<-read.table("features.txt")
testdata<-read.table("test/X_test.txt", col.names = features[,2])
traindata<-read.table("train/X_train.txt", col.names = features[,2])
mergeddata<-rbind(traindata, testdata)
subsetdata<-mergeddata[ , grepl("mean[[:punct:]]|std", names(mergeddata))]
testactivity<-read.table("test/y_test.txt", col.names = c("activity"))
trainactivity<-read.table("train/y_train.txt", col.names = c("activity"))
mergedactivity<-rbind(trainactivity, testactivity)
activities<-read.table("activity_labels.txt")
mergedactivity<-transform(mergedactivity, activity = activities[activity, 2])
testsubjects<-read.table("test/subject_test.txt", col.names = c("subject"))
trainsubjects<-read.table("train/subject_train.txt", col.names = c("subject"))
mergedsubjects<-rbind(trainsubjects, testsubjects)
combineddata<-cbind(mergedsubjects, mergedactivity, subsetdata)
combineddata <- melt(combineddata, id.vars=c("activity","subject"))
summary<-dcast(combineddata, activity + subject ~ variable, mean)
write.table(summary, "summary.txt")